In [ ]:
import pandas as pd
import numpy as np
import io

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving tesla-stock-price.csv to tesla-stock-price.csv

In [ ]:
data = pd.read_csv(io.BytesIO(uploaded['tesla-stock-price.csv']))

In [ ]:
data.head(30)

          date   close         volume    open      high       low
0        11:34  270.49      4,787,699  264.50  273.8800  262.2400
1   2018/10/15  259.59   6189026.0000  259.06  263.2800  254.5367
2   2018/10/12  258.78   7189257.0000  261.00  261.9900  252.0100
3   2018/10/11  252.23   8128184.0000  257.53  262.2500  249.0300
4   2018/10/10  256.88  12781560.0000  264.61  265.5100  247.7700
5   2018/10/09  262.80  12037780.0000  255.25  266.7700  253.3000
6   2018/10/08  250.56  13371180.0000  264.52  267.7599  249.0000
7   2018/10/05  261.95  17900710.0000  274.65  274.8800  260.0000
8   2018/10/04  281.83   9638885.0000  293.95  294.0000  277.6700
9   2018/10/03  294.80   7982272.0000  303.33  304.6000  291.5700
10  2018/10/02  301.02  11699690.0000  313.95  316.8400  299.1500
11  2018/10/01  310.70  21714210.0000  305.77  311.4400  301.0500
12  2018/09/28  264.77  33597290.0000  270.26  278.0000  260.5550
13  2018/09/27  307.52   7337760.0000  312.90  314.9600  306.9100
14  2018/09/26  309.58   7835863.0000  301.91  313.8900  301.1093
15  2018/09/25  300.99   4472287.0000  300.00  304.6000  296.5000
16  2018/09/24  299.68   4834384.0000  298.48  302.9993  293.5800
17  2018/09/21  299.10   5038497.0000  297.70  300.5800  295.3700
18  2018/09/20  298.33   7332477.0000  303.56  305.9800  293.3300
19  2018/09/19  299.02   8264353.0000  280.51  300.0000  280.5000
20  2018/09/18  284.96  16494280.0000  296.69  302.6400  275.5000
21  2018/09/17  294.84   6866208.0000  290.04  300.8700  288.1300
22  2018/09/14  295.20   6757652.0000  288.76  297.3256  286.5200
23  2018/09/13  289.46   6333281.0000  288.02  295.0000  285.1800
24  2018/09/12  290.54  10002150.0000  281.44  292.5000  278.6463
25  2018/09/11  279.44   9161061.0000  279.47  282.0000  273.5500
26  2018/09/10  285.50  14232250.0000  273.26  286.0300  271.0000
27  2018/09/07  263.24  22442310.0000  260.10  268.3500  252.2548
28  2018/09/06  280.95   7472756.0000  284.80  291.1700  278.8800
29  2018/09/05  280.74   7707342.0000  285.05  286.7800  277.1800

In [ ]:
#Split the data into train and test sets
from sklearn.model_selection import train_test_split
train, test = train_test_split(data, test_size=0.5)

In [ ]:
#model
def gradient_descent(m1_now, m2_now, m3_now, b_now, points, L):
  m1_gradient = 0
  m2_gradient = 0
  m3_gradient = 0
  b_gradient = 0

  n = len(points)

  for i in range(n):
    x1 = points.iloc[i].open
    x2= points.iloc[i].high
    x3= points.iloc[i].low
    y = points.iloc[i].close


    m1_gradient += -(2/n) * x1 * (y - (m1_now * x1 + m2_now * x2 + m3_now * x3 + b_now))
    m2_gradient += -(2/n) * x2 * (y - (m1_now * x1 + m2_now * x2 + m3_now * x3 + b_now))
    m3_gradient += -(2/n) * x3 * (y - (m1_now * x1 + m2_now * x2 + m3_now * x3 + b_now))
    b_gradient += -(2/n) * (y - (m1_now * x1 + m2_now * x2 + b_now))

  m1 = m1_now - m1_gradient * L
  m2 = m2_now - m2_gradient * L
  m3 = m3_now - m3_gradient * L
  b = b_now - b_gradient * L
  return m1, m2, m3, b

In [ ]:
#Train the model with train data

m1 = 0
m2 = 0
m3 = 0
b = 0
L = 0.000001
epochs = 30

for i in range(epochs):
  m1, m2, m3, b = gradient_descent(m1, m2, m3, b, train, L)
print(m1, m2, m3, b)

0.3330037440728296 0.3387048816475382 0.32780280006723317 0.006052168248302286

In [ ]:
def calculate_result(m1, m2, m3, b, points):
  n = len(points)

  array = []
  for i in range(n):
    x = points.iloc[i].open
    x2 = points.iloc[i].high
    x3 = points.iloc[i].low
    array.append(m1 * x + m2 * x2 + m3 * x3 + b)
  return array

In [ ]:
result = calculate_result(m1, m2, m3, b, test)

In [ ]:
test['Predictions'] = result
test.head(50)

,date,close,volume,open,high,low,Predictions
731,2015/11/19,221.80,2499593.0000,220.540,226.1900,220.3000,222.273312
285,2017/08/29,347.36,4069303.0000,339.480,349.0500,338.7500,342.322301
508,2016/10/10,200.95,3311340.0000,201.350,204.1400,199.6600,201.648678
321,2017/07/10,316.05,13760290.0000,312.900,317.9400,303.1300,311.257617
176,2018/02/05,333.13,4441166.0000,337.970,344.4700,333.0000,338.383331
692,2016/01/19,204.72,4031271.0000,208.710,210.4700,200.7800,206.610726
224,2017/11/24,315.55,3244065.0000,313.790,316.4100,311.0000,313.615579
597,2016/06/03,218.99,2226110.0000,220.000,221.9400,218.0100,219.903326
46,2018/08/10,355.49,11530510.0000,354.000,360.0000,346.0000,353.242904
662,2016/03/02,188.34,4858631.0000,183.730,188.5200,181.5000,184.537683
302,2017/08/04,356.91,9233295.0000,347.000,357.2700,343.3000,349.102146
606,2016/05/20,220.28,8996546.0000,216.990,220.5500,216.3500,217.886032
430,2017/02/01,249.24,3953105.0000,253.050,253.2000,249.0500,251.672013
215,2017/12/07,311.24,4779590.0000,312.000,318.6341,311.0500,313.789206
98,2018/05/29,283.76,5657153.0000,278.510,286.5000,276.1500,280.312617
427,2017/02/06,257.77,3557600.0000,251.000,257.8200,250.6300,253.072100
214,2017/12/08,315.13,3466088.0000,314.600,316.9800,311.2600,314.163603
51,2018/08/03,348.17,13646640.0000,347.810,355.0000,342.5300,348.350610
63,2018/07/18,323.85,5610085.0000,325.000,325.5000,316.2500,322.148343
157,2018/03/05,333.35,3820702.0000,332.390,337.7500,329.2929,333.033875
558,2016/07/29,234.79,3061574.0000,230.700,235.2800,230.2400,231.993817
99,2018/05/25,278.85,3872621.0000,277.625,279.6400,275.6100,277.517379
650,2016/03/18,232.74,4704761.0000,229.100,234.4800,228.0600,230.475437
288,2017/08/24,352.93,4571574.0000,352.520,356.6600,349.7400,352.844766
682,2016/02/02,182.78,5764817.0000,192.420,193.1200,180.2300,188.573218
579,2016/06/29,210.19,5987120.0000,205.130,211.7800,203.0000,206.589998
339,2017/06/13,375.95,11773370.0000,367.620,376.0000,366.6100,369.953709
408,2017/03/06,251.21,3353601.0000,247.910,251.7000,247.5100,248.947500
147,2018/03/19,313.56,7467890.0000,316.500,320.7500,309.6700,315.552021
741,2015/11/05,231.77,4494944.0000,230.580,234.5843,229.1900,231.374027
388,2017/04/03,298.52,13864850.0000,286.900,299.0000,284.5800,290.103707
283,2017/08/31,355.90,4063330.0000,353.550,358.4400,352.8200,354.800288
530,2016/09/08,197.36,3372293.0000,199.550,199.8900,196.3600,198.528026
287,2017/08/25,348.05,3475186.0000,354.240,355.6900,347.3000,352.289150
635,2016/04/11,249.92,9156404.0000,251.000,258.9900,245.3000,251.721196
716,2015/12/11,217.02,3259114.0000,225.240,225.7500,216.6400,222.489641
492,2016/11/01,190.79,7023674.0000,198.040,198.5000,188.1050,194.848378
134,2018/04/06,299.30,13516530.0000,301.000,309.2800,295.5000,301.860552
217,2017/12/05,303.70,4643708.0000,302.000,308.0000,301.0000,303.562929
652,2016/03/16,221.93,3511873.0000,218.000,222.5800,217.0200,219.129565
684,2016/01/29,191.20,2848929.0000,189.950,193.7400,188.0800,190.533948
711,2015/12/18,230.46,3008057.0000,232.890,235.9000,229.2900,232.621680
53,2018/08/01,300.84,8768099.0000,297.990,303.0000,293.0000,297.911637
97,2018/05/30,291.72,7473590.0000,283.290,295.0050,281.6000,286.571585
259,2017/10/05,355.33,4167913.0000,356.000,357.4350,351.3500,354.793878
202,2017/12/27,311.64,4705084.0000,316.000,317.6800,310.7500,314.699722
303,2017/08/03,347.09,13524270.0000,345.330,350.0000,343.1500,346.034475
228,2017/11/17,315.05,13720830.0000,325.670,326.6700,313.1500,321.751552
681,2016/02/03,173.48,7927640.0000,183.590,183.9400,170.1800,179.229066
162,2018/02/26,357.42,4334500.0000,353.500,359.0000,352.3550,354.820884

In [ ]:
def percentage_change(col1,col2):
    return ((col2 - col1) / col1) * 100

test['error'] = -1 * percentage_change(test['close'],test['Predictions'])
average_error = test['error'].mean()
average_error

0.03791142255637317

In [ ]:
result_old = calculate_result(m1, m2, m3, b, train)
train['Predictions'] = result_old
train['error'] = percentage_change(train['close'],train['Predictions'])
average_error_old = train['error'].mean()
average_error_old

0.009789218943430211